/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    application
    id("checkstyle")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.guava)
    testImplementation("org.assertj:assertj-core:3.23.1")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.9.0")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "ru.job4j.Main"
}

checkstyle {
    toolVersion = "10.3.3"
    configFile = file("checkstyle.xml")
    isShowViolations = true
    isIgnoreFailures = false
}

tasks.named<Checkstyle>("checkstyleMain") {
    source = sourceSets.main.get().allJava
}

tasks.named<Checkstyle>("checkstyleTest") {
    source = sourceSets.test.get().allJava
}